### ISSUE TITLE
Environment a wysyłka maila

### ISSUE THREAD

**Issue by patrykwozinski** [JarJobs/SwiftMailerDatabaseBundle#2]
Hej, pierwszą rzeczą, która mi się rzuciła jest to, że [DatabaseSpool](https://github.com/JarJobs/SwiftMailerDatabaseBundle/blob/master/Resources/config/services.yml) wymaga `kernel.environment`. Czy zamierzacie współdzielić bazę danych między środowiskami? Z góry przyznam, że nie jest to najlepszy pomysł, by na przykład środowisko testowe + developerskie, albo co gorsza produkcyjne - miały wspólną bazę.
A jeżeli nie współdzielicie, to pole staje się zbędne, bo jego wartość będzie zawsze taka sama.

**Comment by fnowacki** [comment]
+1
Fixed in #10
